### ISSUE TITLE
On link screen score always is same as ups, down is always 0. On comment screen down is always 0

### ISSUE THREAD

**Issue by stoicism2323** [Cotix/cReddit#75]
If a comment has more downvotes than upvotes, it manifests as negative sign in front of the number of upvotes.

**Comment by DSMan195276** [comment]
I actually know the problem here, it is due to the change Reddit made a while back which hid the actual number of up and down votes. They made the change backwards compatible by making ups equal to the score, and downs always zero. Since the feature is technically gone, 'ups' and 'downs' could probably be removed, leaving just the score itself.
